nctids_file_name: data/nctids.csv
raw_synonyms_file_name: data/synonyms.csv
processed_synonyms_file_name: data/synonyms.parquet
summaries_file_name: data/brief_summaries.parquet
extraction_nltk_file_name: data/extraction_nltk_results.parquet
